// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATez398Nd68045QbJJFokfQE-ftpDcsLs',
    appId: '1:971887762159:web:584d233dfa11dfe084d91a',
    messagingSenderId: '971887762159',
    projectId: 'pry-logistica-geolocalizacion',
    authDomain: 'pry-logistica-geolocalizacion.firebaseapp.com',
    databaseURL: 'https://pry-logistica-geolocalizacion-default-rtdb.firebaseio.com',
    storageBucket: 'pry-logistica-geolocalizacion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18dECEmQucwM6EGlVcyPHsFWeshakwUQ',
    appId: '1:971887762159:android:5fdd0d130cae6aa684d91a',
    messagingSenderId: '971887762159',
    projectId: 'pry-logistica-geolocalizacion',
    databaseURL: 'https://pry-logistica-geolocalizacion-default-rtdb.firebaseio.com',
    storageBucket: 'pry-logistica-geolocalizacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37VGj-djgRw0MqpMhA3WMQ5xWallwPLw',
    appId: '1:971887762159:ios:2c6545eed479036484d91a',
    messagingSenderId: '971887762159',
    projectId: 'pry-logistica-geolocalizacion',
    databaseURL: 'https://pry-logistica-geolocalizacion-default-rtdb.firebaseio.com',
    storageBucket: 'pry-logistica-geolocalizacion.firebasestorage.app',
    iosBundleId: 'com.example.pryLogisticaGeolocalizacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37VGj-djgRw0MqpMhA3WMQ5xWallwPLw',
    appId: '1:971887762159:ios:2c6545eed479036484d91a',
    messagingSenderId: '971887762159',
    projectId: 'pry-logistica-geolocalizacion',
    databaseURL: 'https://pry-logistica-geolocalizacion-default-rtdb.firebaseio.com',
    storageBucket: 'pry-logistica-geolocalizacion.firebasestorage.app',
    iosBundleId: 'com.example.pryLogisticaGeolocalizacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATez398Nd68045QbJJFokfQE-ftpDcsLs',
    appId: '1:971887762159:web:6986cb326629687d84d91a',
    messagingSenderId: '971887762159',
    projectId: 'pry-logistica-geolocalizacion',
    authDomain: 'pry-logistica-geolocalizacion.firebaseapp.com',
    databaseURL: 'https://pry-logistica-geolocalizacion-default-rtdb.firebaseio.com',
    storageBucket: 'pry-logistica-geolocalizacion.firebasestorage.app',
  );
}
