// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhCswYJ_IyuAfwznQSRoZy6A0TI_krCag',
    appId: '1:722981680903:web:7e0ecdf919e01be816f7a2',
    messagingSenderId: '722981680903',
    projectId: 'chatsito-e6d93',
    authDomain: 'chatsito-e6d93.firebaseapp.com',
    storageBucket: 'chatsito-e6d93.firebasestorage.app',
    measurementId: 'G-LWT1L6CBQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw91zRSEbfnwrCdQuiafH1L5AlNKKyRRI',
    appId: '1:722981680903:android:63d6bca2b575f65516f7a2',
    messagingSenderId: '722981680903',
    projectId: 'chatsito-e6d93',
    storageBucket: 'chatsito-e6d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncmzHZbXwwpyLRHnveDS3R7Fu_SwPXI4',
    appId: '1:722981680903:ios:a9bcd3f09d7a393c16f7a2',
    messagingSenderId: '722981680903',
    projectId: 'chatsito-e6d93',
    storageBucket: 'chatsito-e6d93.firebasestorage.app',
    iosBundleId: 'com.example.pryFirebaseBdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCncmzHZbXwwpyLRHnveDS3R7Fu_SwPXI4',
    appId: '1:722981680903:ios:a9bcd3f09d7a393c16f7a2',
    messagingSenderId: '722981680903',
    projectId: 'chatsito-e6d93',
    storageBucket: 'chatsito-e6d93.firebasestorage.app',
    iosBundleId: 'com.example.pryFirebaseBdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhCswYJ_IyuAfwznQSRoZy6A0TI_krCag',
    appId: '1:722981680903:web:1fb20162d6dbca3716f7a2',
    messagingSenderId: '722981680903',
    projectId: 'chatsito-e6d93',
    authDomain: 'chatsito-e6d93.firebaseapp.com',
    storageBucket: 'chatsito-e6d93.firebasestorage.app',
    measurementId: 'G-L2C34PQV12',
  );
}
